---
framework: mocha
postMerge:
  pattern:
    - "./test/index.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/index.js"
preRun:
  - npm i
postRun:
  - node --version
  - echo "Ba Dum TAS... -_-"
stability:
  consecutive_runs: 5
version: 2.0

